/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.michelin.kstreamplify.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SubKafkaTest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2130524430017734476L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SubKafkaTest\",\"namespace\":\"io.github.michelin.kstreamplify.avro\",\"fields\":[{\"name\":\"subField\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"subSplit\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SubSubKafkaTest\",\"fields\":[{\"name\":\"subSubDateField\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"subSubField\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"subSubIntField\",\"type\":[\"null\",\"int\"],\"default\":null}]}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<SubKafkaTest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SubKafkaTest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SubKafkaTest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SubKafkaTest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SubKafkaTest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SubKafkaTest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SubKafkaTest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SubKafkaTest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SubKafkaTest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private String subField;
  private java.util.List<SubSubKafkaTest> subSplit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SubKafkaTest() {}

  /**
   * All-args constructor.
   * @param subField The new value for subField
   * @param subSplit The new value for subSplit
   */
  public SubKafkaTest(String subField, java.util.List<SubSubKafkaTest> subSplit) {
    this.subField = subField;
    this.subSplit = subSplit;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return subField;
    case 1: return subSplit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: subField = value$ != null ? value$.toString() : null; break;
    case 1: subSplit = (java.util.List<SubSubKafkaTest>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'subField' field.
   * @return The value of the 'subField' field.
   */
  public String getSubField() {
    return subField;
  }


  /**
   * Sets the value of the 'subField' field.
   * @param value the value to set.
   */
  public void setSubField(String value) {
    this.subField = value;
  }

  /**
   * Gets the value of the 'subSplit' field.
   * @return The value of the 'subSplit' field.
   */
  public java.util.List<SubSubKafkaTest> getSubSplit() {
    return subSplit;
  }


  /**
   * Sets the value of the 'subSplit' field.
   * @param value the value to set.
   */
  public void setSubSplit(java.util.List<SubSubKafkaTest> value) {
    this.subSplit = value;
  }

  /**
   * Creates a new SubKafkaTest RecordBuilder.
   * @return A new SubKafkaTest RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new SubKafkaTest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SubKafkaTest RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new SubKafkaTest RecordBuilder by copying an existing SubKafkaTest instance.
   * @param other The existing instance to copy.
   * @return A new SubKafkaTest RecordBuilder
   */
  public static Builder newBuilder(SubKafkaTest other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for SubKafkaTest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SubKafkaTest>
    implements org.apache.avro.data.RecordBuilder<SubKafkaTest> {

    private String subField;
    private java.util.List<SubSubKafkaTest> subSplit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.subField)) {
        this.subField = data().deepCopy(fields()[0].schema(), other.subField);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.subSplit)) {
        this.subSplit = data().deepCopy(fields()[1].schema(), other.subSplit);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SubKafkaTest instance
     * @param other The existing instance to copy.
     */
    private Builder(SubKafkaTest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.subField)) {
        this.subField = data().deepCopy(fields()[0].schema(), other.subField);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subSplit)) {
        this.subSplit = data().deepCopy(fields()[1].schema(), other.subSplit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'subField' field.
      * @return The value.
      */
    public String getSubField() {
      return subField;
    }


    /**
      * Sets the value of the 'subField' field.
      * @param value The value of 'subField'.
      * @return This builder.
      */
    public Builder setSubField(String value) {
      validate(fields()[0], value);
      this.subField = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'subField' field has been set.
      * @return True if the 'subField' field has been set, false otherwise.
      */
    public boolean hasSubField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'subField' field.
      * @return This builder.
      */
    public Builder clearSubField() {
      subField = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subSplit' field.
      * @return The value.
      */
    public java.util.List<SubSubKafkaTest> getSubSplit() {
      return subSplit;
    }


    /**
      * Sets the value of the 'subSplit' field.
      * @param value The value of 'subSplit'.
      * @return This builder.
      */
    public Builder setSubSplit(java.util.List<SubSubKafkaTest> value) {
      validate(fields()[1], value);
      this.subSplit = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subSplit' field has been set.
      * @return True if the 'subSplit' field has been set, false otherwise.
      */
    public boolean hasSubSplit() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subSplit' field.
      * @return This builder.
      */
    public Builder clearSubSplit() {
      subSplit = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SubKafkaTest build() {
      try {
        SubKafkaTest record = new SubKafkaTest();
        record.subField = fieldSetFlags()[0] ? this.subField : (String) defaultValue(fields()[0]);
        record.subSplit = fieldSetFlags()[1] ? this.subSplit : (java.util.List<SubSubKafkaTest>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SubKafkaTest>
    WRITER$ = (org.apache.avro.io.DatumWriter<SubKafkaTest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SubKafkaTest>
    READER$ = (org.apache.avro.io.DatumReader<SubKafkaTest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










