name: Security

on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:

jobs:
  scan-code:
    name: Scan code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Trivy source code
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          limit-severities-for-sarif: true

      - name: Upload Trivy source code report
        if: always()
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
        with:
          sarif_file: trivy-results.sarif
          category: source-code